#!/bin/bash

# This script is responsible for setting up the password on the
# student account and applying this to both the system password
# guacamole and VNC.  The script should run after every reboot
# or AMI initialisation so that we can clone the same AMI over
# multiple servers and have it just run.

# Capture the current instance id

set -euo pipefail

USER_NAME="student"
IMDS="http://169.254.169.254"

# Fetch IMDSv2 token
TOKEN="$(curl -fsS --max-time 2 \
  -X PUT "$IMDS/latest/api/token" \
  -H "X-aws-ec2-metadata-token-ttl-seconds: 21600")"

# Fetch instance-id using token
INSTANCE="$(curl -fsS --max-time 2 \
  -H "X-aws-ec2-metadata-token: $TOKEN" \
  "$IMDS/latest/meta-data/instance-id")"

# Set the system password
echo student:$INSTANCE | sudo chpasswd

# Get an MD5 hashed version of the password
export PWMD=`echo -n $INSTANCE | openssl md5 | sed 's/^.* //'`

# Set up the guacamole user file

echo "<user-mapping>
    <!-- Per-user authentication and config information -->
    <authorize
         username=\"student\"
         password=\"$PWMD\"
         encoding=\"md5\">
       <connection name=\"default\">
         <protocol>vnc</protocol>
         <param name=\"hostname\">localhost</param>
         <param name=\"port\">5901</param>
         <param name=\"password\">$INSTANCE</param>
       </connection>
    </authorize>
</user-mapping>
" > /etc/guacamole/user-mapping.xml

# Set the vnc password
vncpasswd -f <<< $INSTANCE > ~student/.vnc/passwd

# Set the ownership and permissions on the vnc password file
chown -R student:student ~student/.vnc
chmod 600 ~student/.vnc/passwd

# Restart guacamole
# This has been problematic in that guacd wasn't starting properly
# so we're going to be more forceful here.
systemctl stop tomcat10 guacd

# Force kill any guacd processes which are still running.  We need
# the || true in case nothing is there to be killed in which case
# the script would stop because of the set -e at the top
killall -9 guacd || true

# Restart guacd and tomcat10
systemctl restart tomcat10 guacd

# Start VNC
sudo su student -c 'cd /home/student; vncserver -depth 24 -geometry 1280x800'

